#!/usr/bin/python3
import argparse
import os

DEBUGPRINT=print
DEBUGEXIT=exit

#call_name = os.path.basename(__file__)
parser = argparse.ArgumentParser(
prog        = 'scourer.py',
description = 'delete all files in a "list.bad" file generated by Listcopy.py.',
epilog      = 'Have Fun'
)

parser.add_argument('badfiles',
                help='file containing files that failed to copy by listcopy.py',
                metavar='',
                nargs='?',
                action='store'
                )

args = parser.parse_args()


def scrub(listing):
	try:
		with open(listing,'r') as lines:
			for line in lines.readlines():
				line=line[:-1]
				pos=line.find('#')
				path=line[:pos-1]
				print(f'remove: "{path}"',end=' --> ')
				try:
					os.remove(path)
					print ('removed')
				except OSError as e:
					print(f'failed "{e}"')
	except OSError as e:
		exit(f'"{listing}" {e}')


def main() -> None:
	pass


if __name__ == '__main__':
	if args.badfiles:
		scrub(args.badfiles)
		exit(0)
	parser.print_help()